sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker
cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean package

before_deploy:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  - docker build -t openapitools/openapi-petstore .

deploy:
  provider: script
  script: docker push openapitools/openapi-petstore
  on:
    branch: master